### ISSUE TITLE
Woolware isn't by oma

### ISSUE THREAD

**Issue by quickdaffy** [SkiesPlusPlus/SkiddedClients#3]
woolware was made by someone who was impersonating oma, his real account is xAsulo

**Comment by SkiesPlusPlus** [comment]
thanks for the info

**Comment by quickdaffy** [comment]
no, i mean xAsulo is OMA, and Woolware was not made by oma, but by someone impersonating oma

**Comment by SkiesPlusPlus** [comment]
interesting
